/* tslint:disable */
/* eslint-disable */
/**
 * Note Keeper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiNote,
  ApiNoteCreateRequest,
  ApiNoteUpdateDirectoryRequest,
  ApiNoteUpdateRequest,
} from '../models/index';
import {
    ApiNoteFromJSON,
    ApiNoteToJSON,
    ApiNoteCreateRequestFromJSON,
    ApiNoteCreateRequestToJSON,
    ApiNoteUpdateDirectoryRequestFromJSON,
    ApiNoteUpdateDirectoryRequestToJSON,
    ApiNoteUpdateRequestFromJSON,
    ApiNoteUpdateRequestToJSON,
} from '../models/index';

export interface CreatePostRequest {
    apiNoteCreateRequest?: ApiNoteCreateRequest;
}

export interface NoteIdDeleteRequest {
    noteId: string;
}

export interface NoteIdDirectoryPutRequest {
    noteId: string;
    apiNoteUpdateDirectoryRequest?: ApiNoteUpdateDirectoryRequest;
}

export interface NoteIdGetRequest {
    noteId: string;
}

export interface NoteIdPutRequest {
    noteId: string;
    apiNoteUpdateRequest?: ApiNoteUpdateRequest;
}

/**
 * NoteApi - interface
 * 
 * @export
 * @interface NoteApiInterface
 */
export interface NoteApiInterface {
    /**
     * 
     * @param {ApiNoteCreateRequest} [apiNoteCreateRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NoteApiInterface
     */
    createPostRaw(requestParameters: CreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiNote>>;

    /**
     */
    createPost(apiNoteCreateRequest?: ApiNoteCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiNote>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NoteApiInterface
     */
    listGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiNote>>>;

    /**
     */
    listGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiNote>>;

    /**
     * 
     * @param {string} noteId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NoteApiInterface
     */
    noteIdDeleteRaw(requestParameters: NoteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     */
    noteIdDelete(noteId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * 
     * @param {string} noteId 
     * @param {ApiNoteUpdateDirectoryRequest} [apiNoteUpdateDirectoryRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NoteApiInterface
     */
    noteIdDirectoryPutRaw(requestParameters: NoteIdDirectoryPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiNote>>;

    /**
     */
    noteIdDirectoryPut(noteId: string, apiNoteUpdateDirectoryRequest?: ApiNoteUpdateDirectoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiNote>;

    /**
     * 
     * @param {string} noteId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NoteApiInterface
     */
    noteIdGetRaw(requestParameters: NoteIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiNote>>;

    /**
     */
    noteIdGet(noteId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiNote>;

    /**
     * 
     * @param {string} noteId 
     * @param {ApiNoteUpdateRequest} [apiNoteUpdateRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NoteApiInterface
     */
    noteIdPutRaw(requestParameters: NoteIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiNote>>;

    /**
     */
    noteIdPut(noteId: string, apiNoteUpdateRequest?: ApiNoteUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiNote>;

}

/**
 * 
 */
export class NoteApi extends runtime.BaseAPI implements NoteApiInterface {

    /**
     */
    async createPostRaw(requestParameters: CreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiNote>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiNoteCreateRequestToJSON(requestParameters.apiNoteCreateRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiNoteFromJSON(jsonValue));
    }

    /**
     */
    async createPost(apiNoteCreateRequest?: ApiNoteCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiNote> {
        const response = await this.createPostRaw({ apiNoteCreateRequest: apiNoteCreateRequest }, initOverrides);
        return await response.value();
    }

    /**
     */
    async listGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiNote>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiNoteFromJSON));
    }

    /**
     */
    async listGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiNote>> {
        const response = await this.listGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async noteIdDeleteRaw(requestParameters: NoteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new runtime.RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling noteIdDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/{noteId}`.replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async noteIdDelete(noteId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.noteIdDeleteRaw({ noteId: noteId }, initOverrides);
        return await response.value();
    }

    /**
     */
    async noteIdDirectoryPutRaw(requestParameters: NoteIdDirectoryPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiNote>> {
        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new runtime.RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling noteIdDirectoryPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/{noteId}/directory`.replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ApiNoteUpdateDirectoryRequestToJSON(requestParameters.apiNoteUpdateDirectoryRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiNoteFromJSON(jsonValue));
    }

    /**
     */
    async noteIdDirectoryPut(noteId: string, apiNoteUpdateDirectoryRequest?: ApiNoteUpdateDirectoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiNote> {
        const response = await this.noteIdDirectoryPutRaw({ noteId: noteId, apiNoteUpdateDirectoryRequest: apiNoteUpdateDirectoryRequest }, initOverrides);
        return await response.value();
    }

    /**
     */
    async noteIdGetRaw(requestParameters: NoteIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiNote>> {
        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new runtime.RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling noteIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/{noteId}`.replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiNoteFromJSON(jsonValue));
    }

    /**
     */
    async noteIdGet(noteId: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiNote> {
        const response = await this.noteIdGetRaw({ noteId: noteId }, initOverrides);
        return await response.value();
    }

    /**
     */
    async noteIdPutRaw(requestParameters: NoteIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiNote>> {
        if (requestParameters.noteId === null || requestParameters.noteId === undefined) {
            throw new runtime.RequiredError('noteId','Required parameter requestParameters.noteId was null or undefined when calling noteIdPut.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/{noteId}`.replace(`{${"noteId"}}`, encodeURIComponent(String(requestParameters.noteId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ApiNoteUpdateRequestToJSON(requestParameters.apiNoteUpdateRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiNoteFromJSON(jsonValue));
    }

    /**
     */
    async noteIdPut(noteId: string, apiNoteUpdateRequest?: ApiNoteUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiNote> {
        const response = await this.noteIdPutRaw({ noteId: noteId, apiNoteUpdateRequest: apiNoteUpdateRequest }, initOverrides);
        return await response.value();
    }

}
