/* tslint:disable */
/* eslint-disable */
/**
 * Note Keeper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountRegisterApiRequest
 */
export interface AccountRegisterApiRequest {
    /**
     * 
     * @type {string}
     * @memberof AccountRegisterApiRequest
     */
    username?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountRegisterApiRequest
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountRegisterApiRequest
     */
    password?: string | null;
}

/**
 * Check if a given object implements the AccountRegisterApiRequest interface.
 */
export function instanceOfAccountRegisterApiRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AccountRegisterApiRequestFromJSON(json: any): AccountRegisterApiRequest {
    return AccountRegisterApiRequestFromJSONTyped(json, false);
}

export function AccountRegisterApiRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountRegisterApiRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': !exists(json, 'username') ? undefined : json['username'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function AccountRegisterApiRequestToJSON(value?: AccountRegisterApiRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'email': value.email,
        'password': value.password,
    };
}

